openapi: 3.0.1
info:
  title: TimeoutAPI
  description: API Definition of TimeoutAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/timeout
paths:
  /:
    get:
      responses:
        default:
          description: Default response
